---
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
deploy:
  provider: cargo
  token:
    secure: >-
      K6+xlBUEaiy96goOyHmCDi0eaZWYHuB9wmwVZa+qGtSW/6QhjZ++63PpDQrcqFfBWD6O
      /3B+IsLSXZEt5Qfe3+ADZZ60Y1pHM1KIoLBwE2JMP78F+Yl7zdYkMPr0P095CQyufpT0DtfQdBrA
      Sjt3JwIugOI2rzHJbc9hk1fqOXDP9BgniiLFzsNPSeajdh4zYVwuXACwJ1GPLYag6tMRtOs6bmCl
      8vWFo1EVLBkKr2y3AiXsHm3wZVoaxhbwhvjcFnuN6YnW5qjKWW0fxDSrNLPAq6iyIZYuP5+Z3C2Y
      DiceZh2iPmL3upwE+W/6aMBH/II7EIc+e73bSLZXOu0hU/uyDMeZNCQ5KdXQRhGeMpRJh6uQTS48
      OTuKan2fdkJJTgJquU0lik9MmjOXtgrMrE6h/tLiYAl8NFhMM1PBFX8yvN0ffS4GWwB+F5EYhyYU
      ARGdhreOrPdSpimz22dQUvppo/wY46SW3aehamLBZlthcBoqEAbABWKGJyTZmZUPwzkpzQGhNfo3
      NeiPPBcgw4XhbA9E6WPdh1BIPqWrtpyB6WOHBf5SqE3ElliqZz0QbKEh0BAtGDADfUzgF7IGHmWR
      L3lcE3UC9ZQ/JzuITBNQnUmlhBB63c5+thLR70o4TB9MXWmlrdIprDhs4gMUBJv3WVpkqVnQ80qC
      lQ/rqFA=
    on:
      tags: true
---
