brace_style = "PreferSameLine"
condense_wildcard_suffixes = true
edition = "2018"
enum_discrim_align_threshold = 100
error_on_line_overflow = true
error_on_unformatted = true
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hard_tabs = true
ignore = [
  "src/ignore",
  "src/stub",
  "docs"
]
license_template_path = ""
make_backup = false
match_block_trailing_comma = true
merge_imports = true
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
report_fixme = "Never"
report_todo = "Never"
struct_field_align_threshold = 20
trailing_comma = "Never"
use_try_shorthand = true
where_single_line = true
wrap_comments = true
