complete -c godwit -n "__fish_use_subcommand" -s o -l org -d 'Organization (for all operations) (Overrides glyph)'
complete -c godwit -n "__fish_use_subcommand" -s p -l project -d 'Project in organization (for all operations) (Overrides glyph)'
complete -c godwit -n "__fish_use_subcommand" -s q -l quiet -d 'Silence all output'
complete -c godwit -n "__fish_use_subcommand" -s v -l verbose -d 'Debug mode'
complete -c godwit -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c godwit -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c godwit -n "__fish_use_subcommand" -f -a "init" -d 'Setup Godwit working directory'
complete -c godwit -n "__fish_use_subcommand" -f -a "switch" -d 'Switch to target glyph, organization or project'
complete -c godwit -n "__fish_use_subcommand" -f -a "add" -d 'Add projects under Godwit'
complete -c godwit -n "__fish_use_subcommand" -f -a "remove" -d 'Remove projects under Godwit'
complete -c godwit -n "__fish_use_subcommand" -f -a "status" -d 'Display Godwit\'s status'
complete -c godwit -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c godwit -n "__fish_seen_subcommand_from init" -s o -l org -d 'Organization (for all operations) (Overrides glyph)'
complete -c godwit -n "__fish_seen_subcommand_from init" -s p -l project -d 'Project in organization (for all operations) (Overrides glyph)'
complete -c godwit -n "__fish_seen_subcommand_from init" -l headless -d 'Headless setup'
complete -c godwit -n "__fish_seen_subcommand_from init" -l refresh -d 'Purge existing settings before setup'
complete -c godwit -n "__fish_seen_subcommand_from init" -s h -l help -d 'Prints help information'
complete -c godwit -n "__fish_seen_subcommand_from init" -s V -l version -d 'Prints version information'
complete -c godwit -n "__fish_seen_subcommand_from init" -s q -l quiet -d 'Silence all output'
complete -c godwit -n "__fish_seen_subcommand_from init" -s v -l verbose -d 'Debug mode'
complete -c godwit -n "__fish_seen_subcommand_from switch" -s o -l org -d 'Organization (for all operations) (Overrides glyph)'
complete -c godwit -n "__fish_seen_subcommand_from switch" -s p -l project -d 'Project in organization (for all operations) (Overrides glyph)'
complete -c godwit -n "__fish_seen_subcommand_from switch" -l default -d 'Use as default project'
complete -c godwit -n "__fish_seen_subcommand_from switch" -s h -l help -d 'Prints help information'
complete -c godwit -n "__fish_seen_subcommand_from switch" -s V -l version -d 'Prints version information'
complete -c godwit -n "__fish_seen_subcommand_from switch" -s q -l quiet -d 'Silence all output'
complete -c godwit -n "__fish_seen_subcommand_from switch" -s v -l verbose -d 'Debug mode'
complete -c godwit -n "__fish_seen_subcommand_from add" -s o -l org -d 'Organization (for all operations) (Overrides glyph)'
complete -c godwit -n "__fish_seen_subcommand_from add" -s p -l project -d 'Project in organization (for all operations) (Overrides glyph)'
complete -c godwit -n "__fish_seen_subcommand_from add" -s e -l existing -d 'Add existing project (Doesn\'t trigger weaver)'
complete -c godwit -n "__fish_seen_subcommand_from add" -l active -d 'Add as active project'
complete -c godwit -n "__fish_seen_subcommand_from add" -l default -d 'Add as default project'
complete -c godwit -n "__fish_seen_subcommand_from add" -s h -l help -d 'Prints help information'
complete -c godwit -n "__fish_seen_subcommand_from add" -s V -l version -d 'Prints version information'
complete -c godwit -n "__fish_seen_subcommand_from add" -s q -l quiet -d 'Silence all output'
complete -c godwit -n "__fish_seen_subcommand_from add" -s v -l verbose -d 'Debug mode'
complete -c godwit -n "__fish_seen_subcommand_from remove" -s o -l org -d 'Organization (for all operations) (Overrides glyph)'
complete -c godwit -n "__fish_seen_subcommand_from remove" -s p -l project -d 'Project in organization (for all operations) (Overrides glyph)'
complete -c godwit -n "__fish_seen_subcommand_from remove" -s h -l help -d 'Prints help information'
complete -c godwit -n "__fish_seen_subcommand_from remove" -s V -l version -d 'Prints version information'
complete -c godwit -n "__fish_seen_subcommand_from remove" -s q -l quiet -d 'Silence all output'
complete -c godwit -n "__fish_seen_subcommand_from remove" -s v -l verbose -d 'Debug mode'
complete -c godwit -n "__fish_seen_subcommand_from status" -s o -l org -d 'Organization (for all operations) (Overrides glyph)'
complete -c godwit -n "__fish_seen_subcommand_from status" -s p -l project -d 'Project in organization (for all operations) (Overrides glyph)'
complete -c godwit -n "__fish_seen_subcommand_from status" -s h -l help -d 'Prints help information'
complete -c godwit -n "__fish_seen_subcommand_from status" -s V -l version -d 'Prints version information'
complete -c godwit -n "__fish_seen_subcommand_from status" -s q -l quiet -d 'Silence all output'
complete -c godwit -n "__fish_seen_subcommand_from status" -s v -l verbose -d 'Debug mode'
complete -c godwit -n "__fish_seen_subcommand_from help" -s o -l org -d 'Organization (for all operations) (Overrides glyph)'
complete -c godwit -n "__fish_seen_subcommand_from help" -s p -l project -d 'Project in organization (for all operations) (Overrides glyph)'
complete -c godwit -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c godwit -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c godwit -n "__fish_seen_subcommand_from help" -s q -l quiet -d 'Silence all output'
complete -c godwit -n "__fish_seen_subcommand_from help" -s v -l verbose -d 'Debug mode'
